apiVersion: v1alpha1
kind: Role
metadata:
  name: template-feed-public-apis
  labels:
    halo.run/role-template: "true"
    halo.run/hidden: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
  annotations:
    rbac.authorization.halo.run/display-name: "获取订阅源列表"
rules:
  - apiGroups: [ "api.feed.halo.run" ]
    resources: [ "rss-sources" ]
    verbs: [ "list" ]
